package com.sf.sofarmusic.db.search;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SEARCH_RECORD".
 */
@Entity
public class SearchRecord {

    @Id(autoincrement = true)
    private Long id;
    private String word;
    private Integer linkType;
    private String linkUrl;

    @Generated
    public SearchRecord() {
    }

    public SearchRecord(Long id) {
        this.id = id;
    }

    @Generated
    public SearchRecord(Long id, String word, Integer linkType, String linkUrl) {
        this.id = id;
        this.word = word;
        this.linkType = linkType;
        this.linkUrl = linkUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public Integer getLinkType() {
        return linkType;
    }

    public void setLinkType(Integer linkType) {
        this.linkType = linkType;
    }

    public String getLinkUrl() {
        return linkUrl;
    }

    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

}
