package com.sf.sofarmusic.db.search;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SEARCH_RECORD".
*/
public class SearchRecordDao extends AbstractDao<SearchRecord, Long> {

    public static final String TABLENAME = "SEARCH_RECORD";

    /**
     * Properties of entity SearchRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Word = new Property(1, String.class, "word", false, "WORD");
        public final static Property LinkType = new Property(2, Integer.class, "linkType", false, "LINK_TYPE");
        public final static Property LinkUrl = new Property(3, String.class, "linkUrl", false, "LINK_URL");
    }


    public SearchRecordDao(DaoConfig config) {
        super(config);
    }
    
    public SearchRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SEARCH_RECORD\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"WORD\" TEXT," + // 1: word
                "\"LINK_TYPE\" INTEGER," + // 2: linkType
                "\"LINK_URL\" TEXT);"); // 3: linkUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SEARCH_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SearchRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String word = entity.getWord();
        if (word != null) {
            stmt.bindString(2, word);
        }
 
        Integer linkType = entity.getLinkType();
        if (linkType != null) {
            stmt.bindLong(3, linkType);
        }
 
        String linkUrl = entity.getLinkUrl();
        if (linkUrl != null) {
            stmt.bindString(4, linkUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SearchRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String word = entity.getWord();
        if (word != null) {
            stmt.bindString(2, word);
        }
 
        Integer linkType = entity.getLinkType();
        if (linkType != null) {
            stmt.bindLong(3, linkType);
        }
 
        String linkUrl = entity.getLinkUrl();
        if (linkUrl != null) {
            stmt.bindString(4, linkUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SearchRecord readEntity(Cursor cursor, int offset) {
        SearchRecord entity = new SearchRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // word
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // linkType
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // linkUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SearchRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWord(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLinkType(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setLinkUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SearchRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SearchRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SearchRecord entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
