package com.sf.sofarmusic.db.song;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sf.sofarmusic.db.song.SongRecord;

import com.sf.sofarmusic.db.song.SongRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig songRecordDaoConfig;

    private final SongRecordDao songRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        songRecordDaoConfig = daoConfigMap.get(SongRecordDao.class).clone();
        songRecordDaoConfig.initIdentityScope(type);

        songRecordDao = new SongRecordDao(songRecordDaoConfig, this);

        registerDao(SongRecord.class, songRecordDao);
    }
    
    public void clear() {
        songRecordDaoConfig.clearIdentityScope();
    }

    public SongRecordDao getSongRecordDao() {
        return songRecordDao;
    }

}
