package com.sf.sofarmusic.db.song;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SONG_RECORD".
 */
@Entity
public class SongRecord {

    @Id(autoincrement = true)
    private Long id;
    private String songId;

    @Generated
    public SongRecord() {
    }

    public SongRecord(Long id) {
        this.id = id;
    }

    @Generated
    public SongRecord(Long id, String songId) {
        this.id = id;
        this.songId = songId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSongId() {
        return songId;
    }

    public void setSongId(String songId) {
        this.songId = songId;
    }

}
